data:
  dataset: {name: nudity_3739, samples: 7478, type: private}
  datasetLoadOption: full
  kfold: 1
  mapping:
    name:
      options: {Augmentation: true, Height: '200', Normalization: true, Resize: true,
        Scaling: '1', Width: '200', height_shift_range: '0.25', horizontal_flip: true,
        pretrained: None, rotation_range: '180', shear_range: '0.25', vertical_flip: true,
        width_shift_range: '0.25'}
      port: InputPort0
      shape: ''
      type: Image
    rate:
      options: {}
      port: OutputPort0
      shape: ''
      type: Categorical
  numPorts: 1
  samples: {split: 1, test: 0, training: 5982, validation: 1495}
  shuffle: true
model:
  connections:
  - {source: Convolution2D_2, target: MaxPooling2D_1}
  - {source: Convolution2D_1, target: Convolution2D_2}
  - {source: MaxPooling2D_1, target: Dropout_1}
  - {source: Dropout_1, target: Flatten_1}
  - {source: Dense_2, target: Output_1}
  - {source: Dropout_2, target: Dense_2}
  - {source: Dense_1, target: Dropout_2}
  - {source: Flatten_1, target: Dense_1}
  - {source: Input_1, target: Convolution2D_1}
  layers:
  - args: {}
    class: Input
    name: Input_1
    x: 81
    y: 82
  - args: {}
    class: Output
    name: Output_1
    x: 643
    y: 698
  - args: {activation: relu, nb_col: '4', nb_filter: '32', nb_row: '4'}
    class: Convolution2D
    name: Convolution2D_1
    x: 83
    y: 206
  - args: {activation: relu, nb_col: '2', nb_filter: '4', nb_row: '2'}
    class: Convolution2D
    name: Convolution2D_2
    x: 84
    y: 328
  - args: {pool_size: '(2,2)'}
    class: MaxPooling2D
    name: MaxPooling2D_1
    x: 86
    y: 482
  - args: {p: '0.38'}
    class: Dropout
    name: Dropout_1
    x: 85
    y: 604
  - args: {}
    class: Flatten
    name: Flatten_1
    x: 645
    y: 83
  - args: {activation: softsign, output_dim: '40'}
    class: Dense
    name: Dense_1
    x: 646
    y: 203
  - args: {p: '0.68'}
    class: Dropout
    name: Dropout_2
    x: 647
    y: 344
  - args: {activation: softmax, output_dim: '2'}
    class: Dense
    name: Dense_2
    x: 646
    y: 505
params:
  advance_params: true
  batch_size: 285
  is_custom_loss: false
  loss_func: categorical_crossentropy
  num_epoch: 300
  optimizer: {name: Adadelta, rho: '0.98'}
project: nudity_check
